services:
  postgres:
    image: postgres:17-alpine
    container_name: learn-proof-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: learn-proof-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
